version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          name: Install packages
          command: |
            sudo apt-get update
            pyenv versions
            pyenv global 3.7.0
            sudo apt-get install python3-pip
            pip3 install numpy
            pip3 install scipy
            pip3 install html-testRunner
      - run:
          name: Test
          command: |
            python3 test_downsample_audio_signal.py
